"""changes0712

Revision ID: 56181cef66e3
Revises: 0001_initial
Create Date: 2025-12-07 00:10:47.325506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56181cef66e3'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_hackathon_id'), 'participants', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_participants_profile_id'), 'participants', ['profile_id'], unique=False)
    op.alter_column('hackathons', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('hackathons', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hackathons', 'photo_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hackathons', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('hackathons', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('hackathons', 'tags',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hackathons', 'max_teams',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hackathons', 'min_team_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hackathons', 'max_team_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hackathons', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organizers', 'login',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('organizers', 'password_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('uq_organizers_login'), table_name='organizers')
    op.create_unique_constraint(None, 'organizers', ['login'])
    op.create_index(op.f('ix_profile_skills_profile_id'), 'profile_skills', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_skills_skill_id'), 'profile_skills', ['skill_id'], unique=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'about',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('team_members', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('backend', 'frontend', 'mobile', 'ml', 'product', 'designer', name='roletype'),
               nullable=True)
    op.drop_column('team_members', 'approved')
    op.add_column('teams', sa.Column('about', sa.String(length=512), nullable=False))
    op.alter_column('teams', 'hackathon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('teams', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('teams', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('teams', 'hackathon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('teams', 'about')
    op.add_column('team_members', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('backend', 'frontend', 'mobile', 'ml', 'product', 'designer', name='roletype'),
               nullable=False)
    op.alter_column('team_members', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('profiles', 'about',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_profile_skills_skill_id'), table_name='profile_skills')
    op.drop_index(op.f('ix_profile_skills_profile_id'), table_name='profile_skills')
    op.drop_constraint(None, 'organizers', type_='unique')
    op.create_index(op.f('uq_organizers_login'), 'organizers', ['login'], unique=True)
    op.alter_column('organizers', 'password_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('organizers', 'login',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('hackathons', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hackathons', 'max_team_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hackathons', 'min_team_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hackathons', 'max_teams',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hackathons', 'tags',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('hackathons', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('hackathons', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('hackathons', 'photo_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('hackathons', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('hackathons', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_participants_profile_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_hackathon_id'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
