"""changes0812

Revision ID: 5cf23d3137c3
Revises: 56181cef66e3
Create Date: 2025-12-08 02:02:45.517995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf23d3137c3'
down_revision: Union[str, None] = '56181cef66e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INVITE', 'REQUEST', name='invitetypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitestatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_participant_id'), 'invites', ['participant_id'], unique=False)
    op.create_index(op.f('ix_invites_team_id'), 'invites', ['team_id'], unique=False)
    op.alter_column('organizers', 'password_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('hackathons', 'photo_url',
            existing_type=sa.TEXT(),
            nullable=True)
    op.add_column('users', sa.Column('telegram_username', sa.String(), unique=True, index=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizers', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_invites_team_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_participant_id'), table_name='invites')
    op.drop_table('invites')
    op.alter_column('hackathons', 'photo_url',
            existing_type=sa.TEXT(),
            nullable=False)
    op.drop_column('users', 'telegram_username')
    # ### end Alembic commands ###
